<div class="ui-layout-center">
<?php
foreach ( $this->dataTypes as $key1 => $data ) :
	?>
	<div class="process"
		id="acquisition-<?php echo $this->escapeHtml($key1) ?>"
		class="ui-helper-hidden">
		<h2><?php echo $this->translate("Data import")?> : <?php echo $this->escapeHtml($data ['label']) ?> </h2>
		<?php
	if ($data ['annualize'] === true) {
		echo $this->selectYear ( $key1, $this->translate ( "Year" ), $this->firstYear, $this->lastYear );
	}
	foreach ( $data ['configuration'] ['sources'] as $key2 => $source ) {
		$control = $source ['control'];
		echo '<input type="hidden" class="control-script-name" value="' . ucfirst ( $source ['control'] ) . '"/>';
		echo $this->$control ( $key1, $key2, $source, $this->form, $this->cdmFrUploadForm );
	}
	?>
	</div>
<?php
endforeach
;
echo $this->controlScriptNamesHelper ( $this->dataTypes );
?>

<?php

if (isset ( $this->openProcess )) :
	?>
<input type="hidden" id="open-process"
		value="<?php echo $this->openProcess;?>">




<?php 
endif;
if (isset ( $this->selectExecution )) :
	?>
<input type="hidden" id="select-execution"
		value="<?php echo $this->selectExecution;?>">




<?php 
endif;
?>
</div>
